FROM nvidia/cuda:12.8.1-cudnn-devel-ubuntu22.04

# COPY ./requirements/requirements.vllm ./

# pythonのインストール
RUN apt-get update && \
    apt-get install -y python3 python3-pip python3-venv git && \
    pip3 install --upgrade pip

RUN pip install -U pip && \
    pip install vllm==0.10.1.1

# 非ルートで実行するためのユーザを作成
RUN groupadd -r vllmuser && \
    useradd -r -g vllmuser -m -d /home/vllmuser vllmuser

# USERをvllmuserに設定
USER vllmuser

RUN hf download Qwen/Qwen3-4B-Thinking-2507
